# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5bee13d403635d5958da451926941eba4f7c27de2b7aae1a413e8762d8a45630d76981bd2b2760c36b6dccc22c964421754be0e7c157ae1b00148acf9dae1261

test:
  secret_key_base: 1c19085e08ace05f4909f066227c65c027f6bd9a4ce9ebe3e297665d05fa2eafdb6422b471a9459952dc6642070ff8cd9994ecdd9a98a82df3e8b0150a279ec1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
